### GET request with a header
GET http://localhost:8080/headers

###
POST http://localhost:8080/request-body-string-v1
Content-Type: text/plain

hello

###
POST http://localhost:8080/reuqest-body-json-v1
Content-Type: application/json

{"username": "hello","age": "20"}

